### ISSUE TITLE
How to Create the Serial Port?

### ISSUE THREAD

**Issue by ckeyes888** [eklundjon/indigo-exlink#14]
Hey,

Trying to setup the plugin with my Q80T with EZLink port. I’m using the suggested cables but am
not sure how the serial port on the Mac is supposed to be created.
I assume like some other serial devices I have the TV itself when powered on and connected
to the Mac would create it?

Really appreciate any help getting it working!

Thanks,

Carl

**Comment by eklundjon** [comment]
It sounds like you're using a USB-serial adapter?  If so, your Mac won't know anything about the state of the TV; if you're not seeing the serial port on the Mac, you have a driver problem with your serial adapter.  

If you're doing something else, could you share more details about your setup?

**Comment by ckeyes888** [comment]
Jon,

I’m using the USB serial adapter you recommended.
I guess I’m confused on the process of how the serial port is created
on the Mac. With the other USB serial devices I use with Indigo the port seemed to be
created when the device was attached.
Is that what should be happening with the TV?
I assumed since I do have other USB serial ports active and working
that the driver(s) is working.
Maybe some other driver needs to be installed?

Thanks,

Carl

**Comment by eklundjon** [comment]
Oh, do you mean one of the ethernet serial adapters ?

**Comment by ckeyes888** [comment]
No, It’s a USB serial cable. One you recommended from Amazon.

Carl

**Comment by eklundjon** [comment]
The Sabrent one from the 2017 Indigo forum thread?  If not, could you share the link?

**Comment by ckeyes888** [comment]
These are the two I'm using.
https://www.amazon.com/gp/product/B0753HBT12/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

https://www.amazon.com/gp/product/B004T9BBJC/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

Thanks,

Carl

**Comment by eklundjon** [comment]
The Amazon comments on your USB-Serial adapter suggest it's a Prolific chipset, which has been reported to have trouble with newer versions of OS X.  Did you check for an updated driver from the manufacturer?

You'll need to get the serial adapter working before you can start trying out the EX-Link port on your TV or the Indigo plugin.

I don't know specifically what chipset your adapter has, but it appears at least one of the Prolific chipsets has a driver that's claimed to work on Catalina https://plugable.com/drivers/prolific/

**Comment by ckeyes888** [comment]
Thanks Jon. I'll give that a try tomorrow.

Carl

**Comment by eklundjon** [comment]
> Hey Jon,
> 
> Bingo on the driver update. All working well now...thanks. bunch!
> 
> Carl
